engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
        # mass_threshold: 30
      - javascript
    exclude_paths:
    - 'spec/**/*'
    - 'vendor/**/*'
  eslint:
    enabled: true
    exclude_paths:
    - 'vendor/**/*'
  fixme:
    enabled: true
    exclude_paths:
    - 'vendor/**/*'
  reek:
    enabled: true
    exclude_paths:
    - 'db/migrate/*'
  rubocop:
    enabled: true
  scss-lint:
    enabled: true

ratings:
  paths:
  - app/**
  - lib/**
  - '**.rb'
