language: ruby
bundler_args: "--without development:production"
cache: bundler
sudo: false
script: bundle exec rspec
rvm:
- 2.3.1
deploy:
  provider: heroku
  app: ohana-staging
  strategy: git
  api_key:
    secure: occyVXAT6AznUMneNmA9AsxHxnto+HUxwBoNpMiAAm0OCj3PtGfvvQho94hGwnZiAfsbTt3Y6NyGLspQCJuSsazgx2FrXuG3h/XlyyqjZ6EplG1leWSnp9rYic2q1itUe6dqRZWW7FjNIee0iVs7CxGLR/vaYoDzxYDegZ1y9p4=
env:
  global:
  - OHANA_API_ENDPOINT=http://smc-ohana-api-test.herokuapp.com/api
  - DOMAIN_NAME=lvh.me
