language: ruby
bundler_args: "--without development:production"
cache: bundler
sudo: false
script: bundle exec rspec
rvm:
- 2.1.5
deploy:
  provider: heroku
  app: ohana-staging
  strategy: git
  api_key:
    secure: occyVXAT6AznUMneNmA9AsxHxnto+HUxwBoNpMiAAm0OCj3PtGfvvQho94hGwnZiAfsbTt3Y6NyGLspQCJuSsazgx2FrXuG3h/XlyyqjZ6EplG1leWSnp9rYic2q1itUe6dqRZWW7FjNIee0iVs7CxGLR/vaYoDzxYDegZ1y9p4=
env:
  global:
  - S3_BUCKET_NAME=gems-for-travis
  - OHANA_API_ENDPOINT=http://smc-ohana-api-test.herokuapp.com/api
  - secure: AQX/bYCvfEqZOAxXv3u4TIFdAvyCqFS0pnpmL0gPEPTI6SurTzpzC/NE6fKMc7In23N83kp25iigajiz9ZLk1QTr3Ko5LKNxsLfTCT4Pg2xmTx9eU0GvWO3ghx2iq+Dh7v43VQDRXd/q2ywW+rfN2t/fjimS0wbLWu7++UmIOjU=
  - DOMAIN_NAME=lvh.me
