language: ruby
rvm:
- 2.1.1
services:
before_script:
notifications:
  campfire:
    rooms:
    - secure: b20Ulu9dgqeC4YrnCDadz1JudFha77wR6gAsMWqWg7HMK4aXuJjimr/ag/iLk0ouTZRAM26LIfGXzVu5ke/13q5xdVCgUnOZRdq8iysK1S0H7saZ2nV5oXvN9b5HfIZjpIoMIiBKvpsLDknf+fgqn2gGIM2fk72A8+XbHF6VVH4=
    on_success: never
    on_failure: always
deploy:
  provider: heroku
  app: ohana-staging
  strategy: git
  api_key:
    secure: occyVXAT6AznUMneNmA9AsxHxnto+HUxwBoNpMiAAm0OCj3PtGfvvQho94hGwnZiAfsbTt3Y6NyGLspQCJuSsazgx2FrXuG3h/XlyyqjZ6EplG1leWSnp9rYic2q1itUe6dqRZWW7FjNIee0iVs7CxGLR/vaYoDzxYDegZ1y9p4=
env:
  global:
  - secure: E7pU+I2VhRfS3g3Fn8sWNF3ecrMG0PkNJ4CMrIwV0mnhtTQGIcI2k6MrMPYcms04nCn8lmd6iH+ey8Yjovva3O2WmttRoEpCNORd6oGQYkSafLK+QyAJYSJ6tZ+aIHHiJKQ+z6O13LlaLNHEJqLq0SQ9uYcF+ZWDx58u0Ed/v5Q=
  - secure: A56coF7dN9fnPqX1O5JELVPl+/FnocWH+C/0W60gtQzOocWizNFQW7ri002IUPIojYh4b2XZqEtWZ20RdXdaNc7+YBC86SAqBd/WxbhlYXGEOOs14lnrSk/SezHUGjBm/ZmYoRXjH5VoXtqn95LRPseuVbLkli0yCAlUz/+lvZg=
