language: ruby
rvm:
- 2.0.0
services:
before_script:
notifications:
  campfire:
    rooms:
    - secure: |-
        eEuzoYFXLPeIMt+zHGzZp6XCvbfxRDe8FA3kVwrNRB0zoOktPRZXD9O8ng2z
        x2Yg8C7i1unstuW0bjPvwphpdxJOTFSxliw6P4Xk1Y9HnTYQqqUbDat/zL9c
        AyjYezuRQgYFSBP2BgNZ2RL9RiLSyLQBWhcHGB0yBS6rsheKWbk=
    on_success: never
    on_failure: always
deploy:
  provider: heroku
  app: ohana-staging
  api_key:
  - secure: |-
      snkEoAaiMCqlk2KtkNDRQ8dEWSmbhY3bYQgraO70LXDtiey1+iusC0hfuHe2
      dlmMwWjB7LCCBWGReY7nf6WzZf0oAznyYwIhSDG9pb5mtAr8xINvacfPY8Fg
      B/sYeZYnHQ1YB4wDl6ef6x3ugYU+WG/eoaN2uYcLFL23l9J99IQ=
env:
  matrix:
    secure: ZhrMOK9JCzqqiI3mHBNh/g/bUWEZe+SXn91eZuU0zdFKrUlCRwglhABiIf+9a1Ysk1aB0g4LO4tNTV0ku7cdQUHeNabueho88qUKyDj70QB05xHEgtcjelgpD2F9InVi8D47S9UG6LBf9gJAXGN7UTw2CH+sm9q5SLbrKb9fszo=
