bundler_args: "--without development:production"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
language: ruby
rvm:
- 2.1.1
notifications:
  campfire:
    rooms:
    - secure: |-
        eEuzoYFXLPeIMt+zHGzZp6XCvbfxRDe8FA3kVwrNRB0zoOktPRZXD9O8ng2z
        x2Yg8C7i1unstuW0bjPvwphpdxJOTFSxliw6P4Xk1Y9HnTYQqqUbDat/zL9c
        AyjYezuRQgYFSBP2BgNZ2RL9RiLSyLQBWhcHGB0yBS6rsheKWbk=
    on_success: never
    on_failure: always
  webhooks: http://cfa-project-monitor.herokuapp.com/projects/67f80d53-afb0-4344-bd40-2644f55a4462/status