language: ruby
rvm:
- 2.0.0
services:
before_script:
notifications:
  campfire:
    rooms:
    - secure: b20Ulu9dgqeC4YrnCDadz1JudFha77wR6gAsMWqWg7HMK4aXuJjimr/ag/iLk0ouTZRAM26LIfGXzVu5ke/13q5xdVCgUnOZRdq8iysK1S0H7saZ2nV5oXvN9b5HfIZjpIoMIiBKvpsLDknf+fgqn2gGIM2fk72A8+XbHF6VVH4=
    on_success: never
    on_failure: always
deploy:
  provider: heroku
  app: ohana-staging
  api_key:
    secure: Xi9OujdxI7Tg1iuuBIsM949fXwWJpwktoSWcI1/tOkjKKQCwoLSQCnIaQVmkNyS52Y9hsFHdF8pmE7giby5iqXWVGEWxE/a5P1tCzDxEiO2TFdU3MMqNNmfo7v1lgCl7y+jiSn35zr4wskRdULyUTqn9zwoEMYqRSYolkVx8p/E=
env:
  matrix:
  - secure: E7pU+I2VhRfS3g3Fn8sWNF3ecrMG0PkNJ4CMrIwV0mnhtTQGIcI2k6MrMPYcms04nCn8lmd6iH+ey8Yjovva3O2WmttRoEpCNORd6oGQYkSafLK+QyAJYSJ6tZ+aIHHiJKQ+z6O13LlaLNHEJqLq0SQ9uYcF+ZWDx58u0Ed/v5Q=
