bundler_args: "--without development:production"
install: bin/wad
script: bundle exec rspec
language: ruby
rvm:
- 2.1.2
notifications:
  campfire:
    rooms:
    - secure: b20Ulu9dgqeC4YrnCDadz1JudFha77wR6gAsMWqWg7HMK4aXuJjimr/ag/iLk0ouTZRAM26LIfGXzVu5ke/13q5xdVCgUnOZRdq8iysK1S0H7saZ2nV5oXvN9b5HfIZjpIoMIiBKvpsLDknf+fgqn2gGIM2fk72A8+XbHF6VVH4=
    on_success: never
    on_failure: always
deploy:
  provider: heroku
  app: ohana-staging
  strategy: git
  api_key:
    secure: occyVXAT6AznUMneNmA9AsxHxnto+HUxwBoNpMiAAm0OCj3PtGfvvQho94hGwnZiAfsbTt3Y6NyGLspQCJuSsazgx2FrXuG3h/XlyyqjZ6EplG1leWSnp9rYic2q1itUe6dqRZWW7FjNIee0iVs7CxGLR/vaYoDzxYDegZ1y9p4=
env:
  global:
  - S3_BUCKET_NAME=gems-for-travis
  - OHANA_API_ENDPOINT=http://smc-ohana-api-test.herokuapp.com/api
  - secure: AQX/bYCvfEqZOAxXv3u4TIFdAvyCqFS0pnpmL0gPEPTI6SurTzpzC/NE6fKMc7In23N83kp25iigajiz9ZLk1QTr3Ko5LKNxsLfTCT4Pg2xmTx9eU0GvWO3ghx2iq+Dh7v43VQDRXd/q2ywW+rfN2t/fjimS0wbLWu7++UmIOjU=
  - DOMAIN_NAME=lvh.me
