---
http_interactions:
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?action=index&controller=organizations&keyword=asdfg&kind=Human%20Services&location=Custom%20Value&service_area=smc&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Cache-Control:
      - no-cache
      Content-Type:
      - application/json
      Date:
      - Wed, 02 Apr 2014 05:38:04 GMT
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - 327e9a5d-4b75-45be-bcde-3da672ffc773
      X-Runtime:
      - '0.033407'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '68'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"error":"bad request","description":"Invalid ZIP code or address."}'
    http_version: 
  recorded_at: Wed, 02 Apr 2014 05:38:04 GMT
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?keyword=asdfasg
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Wed, 02 Apr 2014 05:38:05 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      X-Current-Page:
      - '1'
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - 44da27c4-8b1e-43e5-8f33-d32e58f9b9d2
      X-Runtime:
      - '0.018183'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Wed, 02 Apr 2014 05:38:05 GMT
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?action=index&controller=organizations&keyword=asdfg&kind=Human%20Services&service_area=smc&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Wed, 02 Apr 2014 05:38:06 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      X-Current-Page:
      - '1'
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - 5745e353-bcba-4179-b3e2-104bfa4ec8fe
      X-Runtime:
      - '0.021833'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Wed, 02 Apr 2014 05:38:06 GMT
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&kind=Human%20Services&service_area=smc&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Wed, 02 Apr 2014 05:47:06 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      X-Current-Page:
      - '1'
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - 5a5a4f3b-a745-4383-b680-699303f9b83f
      X-Runtime:
      - '0.028983'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Wed, 02 Apr 2014 05:47:06 GMT
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&kind=Human%20Services&org_name=Custom%20Value&service_area=smc&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Wed, 02 Apr 2014 06:07:11 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      X-Current-Page:
      - '1'
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - ddce416f-0961-4619-85ac-e7780d7bbb25
      X-Runtime:
      - '0.031691'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Wed, 02 Apr 2014 06:07:11 GMT
recorded_with: VCR 2.8.0
