---
http_interactions:
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?action=index&controller=organizations&keyword=asdfg&kind=Human%20Services&service_area=smc&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Wed, 02 Apr 2014 05:38:04 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      X-Current-Page:
      - '1'
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - da86945f-5fec-439f-be49-e47f5b9b5ec2
      X-Runtime:
      - '0.035076'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Wed, 02 Apr 2014 05:38:04 GMT
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&kind=Human%20Services&service_area=smc&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Wed, 02 Apr 2014 05:47:18 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      X-Current-Page:
      - '1'
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - 0d128fdb-7fb4-4225-912f-091a8f9485c3
      X-Runtime:
      - '0.021944'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Wed, 02 Apr 2014 05:47:18 GMT
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&kind=Human%20Services&org_name=Custom%20Value&service_area=smc&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Wed, 02 Apr 2014 05:56:19 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      X-Current-Page:
      - '1'
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - 0c734b18-4c3f-422b-a824-0a81cb6144b1
      X-Runtime:
      - '0.036817'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Wed, 02 Apr 2014 05:56:19 GMT
recorded_with: VCR 2.8.0
