---
http_interactions:
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?action=index&controller=organizations&keyword=asdfg&kind=Human%20Services&service_area=smc&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Wed, 02 Apr 2014 05:38:46 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      X-Current-Page:
      - '1'
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - a0ed1b30-abfb-437a-910a-47f8d76c6b1d
      X-Runtime:
      - '0.025655'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Wed, 02 Apr 2014 05:38:46 GMT
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&kind=Human%20Services&service_area=smc&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Wed, 02 Apr 2014 05:46:57 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      X-Current-Page:
      - '1'
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - 4acfa140-758f-4552-918d-5a0d7c4815d7
      X-Runtime:
      - '0.025860'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Wed, 02 Apr 2014 05:46:57 GMT
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&kind=Human%20Services&location=Custom%20Value&service_area=smc&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Cache-Control:
      - no-cache
      Content-Type:
      - application/json
      Date:
      - Wed, 02 Apr 2014 05:56:20 GMT
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - ff25a3d5-56ef-40b6-8238-847028858b2d
      X-Runtime:
      - '0.073012'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '68'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"error":"bad request","description":"Invalid ZIP code or address."}'
    http_version: 
  recorded_at: Wed, 02 Apr 2014 05:56:20 GMT
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?api_token=<API_TOKEN>&keyword=asdfasg
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Wed, 02 Apr 2014 05:56:20 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      X-Current-Page:
      - '1'
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - d06f681c-13e5-46a4-9594-4fd14e1bd7b1
      X-Runtime:
      - '0.017532'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Wed, 02 Apr 2014 05:56:20 GMT
recorded_with: VCR 2.8.0
