# First, copy this file to a new one called "application.yml" in the same
# config directory.

# This file is used by the "figaro" gem to allow you to store and use
# environment variables in the app without having to set them via the
# command line each time you run the app in development.
# Read more about figaro here: https://github.com/laserlemon/figaro

# Note that changes to this file will require a server restart to take effect.

# Each entry sets a local environment variable and overrides ENV variables
# in the Unix shell. For example, setting:
# OHANA_API_ENDPOINT: http://api.smc-connect.org
# makes "http://api.smc-connect.org" available as
# ENV["OHANA_API_ENDPOINT"] in the app. See config/initializers/ohanapi.rb
# for a usage example.

# Set this to the URL for your instance of the Ohana API.
# This environment variable is required.
OHANA_API_ENDPOINT: http://api.smc-connect.org

# This setting is used for the Google translation feature.
# The "DOMAIN_NAME" environment variable should be set to your app's
# domain name, without the "www" subdomain, unless you're using a Heroku
# domain, in which case you should set it to your full Heroku domain name,
# such as "ohana-web-search-demo.herokuapp.com".
# If you have a custom domain name, like "www.smc-connect.org", that
# means setting it to "smc-connect.org".
#
# In development, it should only be set to a 2-level domain name,
# like "lvh.me", or "myapp.dev" if you're using Pow.
# Translation won't work with "localhost", so please open the site
# locally via http://lvh.me:{port number}
#
# Read more about lvh.me here:
# http://matthewhutchinson.net/2011/1/10/configuring-subdomains-in-development-with-lvhme
# Pow should work too if you prefer that: http://pow.cx/
DOMAIN_NAME: lvh.me

# If you choose to turn on rate limiting in your instance of Ohana API,
# obtain an API Token for this app from the developer portal of the API,
# then replace "changeme" with the actual token below.
# OHANA_API_TOKEN: changeme

# If you would like your users to be able to type in search keywords
# in the language of their choice, you will need to sign up for a paid
# Google Translate API account. Pricing details are here:
# https://developers.google.com/translate/v2/pricing
# Once you obtain your API Token, enter it below to test the translation
# in development.
# GOOGLE_TRANSLATE_API_TOKEN: Your_API_Token

# To allow users to customize the translations on your site include a
# Google Translate Customization website code. This code is used to verify
# ownership for the Google Website Translator so that custom translations are
# saved for the site. The tag appears in the HTML head and looks like this:
# <meta name="google-translate-customization" content="Your Website Code." />
#
# This code is generated by adding your site to your Google Account
# via the Google Website Translator Widget Wizard at
# https://translate.google.com/manager/website/suggestions
# and clicking "Get Code" when prompted.
# GOOGLE_TRANSLATE_CUSTOMIZATION_CODE: Your_Website_Code_from_Google

###############################################################################
#
# SETTINGS FOR TESTS. PLEASE DO NOT MODIFY UNLESS YOU KNOW WHAT YOU ARE DOING.
#
###############################################################################

test:
  OHANA_API_ENDPOINT: http://smc-ohana-api-test.herokuapp.com/api
  OHANA_API_TOKEN: ~
