# This file is used by the "figaro" gem to allow you to store and use
# environment variables in the app without having to set them via the
# command line each time you run the app in development.

# Read more about figaro here: https://github.com/laserlemon/figaro

# First, rename this file to "application.yml". It should already be listed in
# .gitignore, but if not, make sure to add it there to keep your sensitive info
# (such as API keys and passwords) secret!

# Each entry sets a local environment variable and overrides ENV variables
# in the Unix shell. For example, setting:
# OHANA_API_ENDPOINT: http://ohana-api-demo.herokuapp.com/api
# makes "http://ohana-api-demo.herokuapp.com/api" available as
# ENV["OHANA_API_ENDPOINT"] in the app. See config/initializers/ohanapi.rb
# for a usage example.

# Add application configuration variables here, as shown below.

OHANA_API_ENDPOINT: http://ohana-api-demo.herokuapp.com/api
DOMAIN_NAME: lvh.me

# If you choose to turn on rate limiting in your instance of Ohana API,
# obtain an API Token for this app, then replace "changeme" with the
# actual token below to test that the token works in development.
OHANA_API_TOKEN: changeme

# If you would like your users to be able to type in search keywords
# in the language of their choice, you will need to sign up for a paid
# Google Translate API account. Pricing details are here:
# https://developers.google.com/translate/v2/pricing
# Once you obtain your API Token, enter it below to test the translation
# in development.
#GOOGLE_TRANSLATE_API_TOKEN: Your_API_Token