modules:
  - name: 'routes/home/index'
  - name: 'routes/about/index'
  - name: 'routes/organizations/index'
  - name: 'routes/organizations/show'

paths:
  jquery: 'jquery-min'
  domReady: 'requirejs/domReady'
  async: 'requirejs/async'
  enquire: 'enquire.min'
  Modernizr: 'polyfills/modernizr.min'
  modernizrSelectors: 'polyfills/modernizr.selectors'
  classList: 'polyfills/remy/classList'
  addEventListener: 'polyfills/addEventListener'
  trim: 'polyfills/trim'
  gmaps: 'google/gmap'
  gInfoBox: 'google/infobox'

shim:
  'Modernizr':
    exports: 'Modernizr'
  'modernizrSelectors':
    dep: ['Modernizr']
    exports: 'ModernizrSelectors'
  'checked':
    dep: ['jquery']
    exports: 'pfChecked'
  'gInfoBox':
    dep: ['gmaps']
    exports: 'gInfoBox'

# needs to always be set to true for IE support
# see http://requirejs.org/docs/api.html#ieloadfail
enforceDefine: true

# amount of time to wait before timing out. 7 seconds is default.
waitSeconds: 200