paths:
  enquire: 'enquire.min'
  domReady: 'requirejs/domReady'
  async: 'requirejs/async'

modules:
  - name: 'routes/home/index'
  - name: 'routes/about/index'
  - name: 'routes/organizations/index'
  - name: 'routes/organizations/show'